@ comment
gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of GAMERS!\p"
	.string "My name is MATPAT.\p"
	.string "But everyone calls me the GAME\n"
	.string "THEORIST.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “GAMER.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as GAMERS.\p"
	.string "We normies live alongside GAMERS,\n"
	.string "they typically live inside the\l"
	.string "basements of humans they call their parents.\p"
	.string "At times we dain to interact as\n"
	.string "playmates, and at times as\l"
	.string "player two in CO-OP GAMES.\p"
	.string "And sometimes, they band together\n"
	.string "and battle others like them,\l"
 	.string "in hypercompetitive button mashing.\p"

	.string "But despite our closeness, we don't\n"
	.string "know everything about GAMERS.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding GAMERS.\p"
	.string "To unravel GAMING mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "home state of OHIO.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own GAMING adventure\n"
	.string "is about to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of GAY{PAUSE 5}$"
